### ISSUE TITLE
continued session DoS recovery

### ISSUE THREAD

**Issue by flihp** [intel/tpm2-abrmd#200]
By allowing sessions to survive beyond the lifetime of a connection we're creating a possible DoS scenario. The general flow would go something like:
1. create connection
2. create session
3. save session
4. goto 2 until TPM runs out of sessions
5. close connection

At the end of this no other connection will be able to create sessions.

One possible mitigation would be limiting the number of sessions a connection can open. Circumventing this will only require the attacker be able to create new connections / processes. So some sane maximums on the number of sessions per connection is a necessary but not sufficient to prevent a DoS. We'll also need a mechanism to allow an administrator to flush all abandoned sessions as a way to recover the system

**Comment by martinezjavier** [comment]
@flihp did you see my comment [here](https://github.com/01org/tpm2-tools/issues/510#issuecomment-332485089)?

The relevant part for this discussion is:

> On a TPM2_StartAuthSession() command, it could be that the TPM doesn't have a free handle to assign to a session. In this case, the TPM can either return a TPM_RC_SESSION_HANDLES or TPM_RC_SESSION_MEMORY response code. In case of the former, the resource manager is supposed to flush a session and in case of the latter, it's supposed to flush a transient object.


> I can think of a design on which objects are flushed (since these can always be loaded) but sessions are kept active. If the resource manager gets a TPM_RC_SESSION_HANDLES, then it can do some cleanup and retry the command. For example it may use a LRU algorithm to remove old/stale sessions. That way resource exhaustion won't happen.
> 
> AFAICT neither the tpm2-abrmd nor the kernel resource manager handle these response codes currently.

**Comment by flihp** [comment]
I did see the thread, didn't see these specifics. Thanks for pull that over here. LRU algorithms like this sounds reasonable. Do you think that this could turn the DoS into a race if misbehaving process(es) just do a bit of work to keep their sessions more active than another user?

I guess in this case 'active' doesn't mean 'used'. Really it's a measure of the time between when a continued session was saved to when the resource limit is exceeded. If we limit the logic to cover only 'continued' sessions then it sounds safe enough to me.

**Comment by martinezjavier** [comment]
> I did see the thread, didn't see these specifics. Thanks for pulling that over here. LRU algorithms like this sounds reasonable. Do you think that this could turn the DoS into a race if misbehaving process(es) just do a bit of work to keep their sessions more active than another user?

To be honest I didn't give too much thought to this. More than my suggestion on the implementation details (I was mostly thinking aloud in that thread), I wanted to point out the TPM_RC_SESSION_HANDLES response code in case it may be useful for your DoS prevention code.

**Comment by flihp** [comment]
No worries @martinezjavier, I'm "shooting from the hip" here as well. I like the LRU method since it doesn't require any admin intervention or additional plumbing like an external command to trigger flushing would. I'll prototype something up and see how complicated it gets :smile:

**Comment by martinezjavier** [comment]
@flihp I think that confuses me is that in your mentioned DoS scenario as well as the integration test in PR #195, you talk about saved sessions. But IIUC the issue, then is not only about saved sessions but created sessions.

In other words, sessions should remain "alive" (a.k.a not flushed) regardless if were saved or not. So sessions should only be flushed when:

1. An explicit call to TPM2_FlushContext passing a flushHandler to flush.
2. A command that has a TPM_ST_SESSIONS tag and the session continueSession attribute CLEAR.
3. The TPM2 returning TPM_RC_SESSION_HANDLES when a sessions is attempt to be created with TPM2_StartAuthSession (is still not clear to me how to choose the correct old session to flush, this seems like the kernel out-of-memory killer... where you could get unpleasant surprises).

So you should extend not only to check if a previous saved session context can be saved but also if the handle of a previous (not saved) sessions could be used.

**Comment by martinezjavier** [comment]
> I like the LRU method since it doesn't require any admin intervention or additional plumbing like an external command to trigger flushing would. I'll prototype something up and see how complicated it gets

Great, I'll try to do a review once you have it. I'm very far from being an expert on this, but I've read so many times the context management part of the spec that I hope I could be of any help :smile:

**Comment by williamcroberts** [comment]
Wouldn't the DoS scenario already exist if I have a client that just stays connected and creates MAX sessions?

**Comment by flihp** [comment]
responding to comment from @martinezjavier: https://github.com/01org/tpm2-abrmd/issues/200#issuecomment-333682494

Sounds like the approach you suggest sort of flips the logic around a bit: Instead of requiring a connection to explicitly save a session for it to be 'continued' you're suggesting instead that we continue all sessions from a context unless they've been explicitly flushed by the connection owner? Do I have that right?

The problem that I have with this approach is that we're not saving users any work on the common case. The common case being: A connection creates sessions, uses them and then closes down the connection w/o flushing said context. I think what we'd see with this approach is every session being abandoned by a connection when it's closed (no one wants to clean up after themselves) but never being continued by another connection. The LRU algorithm or something similar when implemented would clean this up but we'd eventuaully end up in the situation where every new session created would require cleaning out an old session which I'm not wild about.

Also this would allow any connection that comes along after an earlier connection is closed to take over a session by guessing the handle. I'd much rather a connection need to be in possession of the context blob in order to continue a session. This requires that the context blob be passed to the holder of this new connection explicitly. This will allow any number of access control things be used to constrain the mechanism used to pass the blob. SELinux would be useful here maybe?

**Comment by flihp** [comment]
replying to comment from @williamcroberts: https://github.com/01org/tpm2-abrmd/issues/200#issuecomment-333927834

Currently we don't implement restrictions on session creation. So there's a DoS potential there flat out. I think this is a separate issue though and one that can be resolved using a similar approach as the limits we do place on transient objects. If there's a fixed number of sessions that the TPM can have saved at a time (~64?) then we can make sure we're under this limit through a combination of connection limits and limits on sessions per connection.

**Comment by williamcroberts** [comment]
@flihp I'm just saying that the DoS issues already exists, and this really doesn't compound that issue very much.

**Comment by martinezjavier** [comment]
> Sounds like the approach you suggest sort of flips the logic around a bit: Instead of requiring a connection to explicitly save a session for it to be 'continued' you're suggesting instead that we continue all sessions from a context unless they've been explicitly flushed by the connection owner? Do I have that right?

@flihp That's correct.

I didn't find in any part of the specification an explicit relation between the connections and the sessions. It seems to me as if the TPM2 state is somehow independent on how the TCTI layer sends commands to the TPM2.

> The problem that I have with this approach is that we're not saving users any work on the common case. The common case being: A connection creates sessions, uses them and then closes down the connection w/o flushing said context. I think what we'd see with this approach is every session being abandoned by a connection when it's closed (no one wants to clean up after themselves) but never being continued by another connection. The LRU algorithm or something similar when implemented would clean this up but we'd eventuaully end up in the situation where every new session created would require cleaning out an old session which I'm not wild about.

Kept in mind that sessions used by commands without the continueSession SET will be flushed automatically. So this is only when the last command **explicitly** asked for the connection to be alive after the command ends.

Now, if a user needs to do a TPM2_ContextSave() anyways, the continueSession attribute seems to be less useful to me.

It's true though that a user can establish a connection, create a lot of sessions and then close the connection. But to prevent those spammy users, maybe the LRU algorithm could have some heuristics and for example penalize sessions that were created in the same connection but never used or something along those lines?

> Also this would allow any connection that comes along after an earlier connection is closed to take over a session by guessing the handle. I'd much rather a connection need to be in possession of the context blob in order to continue a session. This requires that the context blob be passed to the holder of this new connection explicitly. This will allow any number of access control things be used to constrain the mechanism used to pass the blob. SELinux would be useful here maybe?

To be clear, I'm **not** against only keeping the sessions whose context was saved. I just want this to be a deliberate and documented design decision rather than a consequence of only supporting saved sessions.

If that's the case (and security is a very good point indeed) then we should review the assumptions made currently by the tpm2-tools (which in a way are a reference implementation for people to know how the tpm2-tss should be used).

For example, the tpm2_createpolicy tool has a `-e, --extend-policy-session` option that prints the session handle, i.e: `EXTENDED_POLICY_SESSION_HANDLE: 0x03000000`. That's on the assumption that the next command will be able to take that session handle and use it (most tpm2_tools have a `-S, --input-session-handle` for that).

This worked from the lua shell (or any other execution environment) just because the shell kept the connection open. But it obviously doesn't work from the command shell since a new connection is used for each command.

So if only sessions with saved context are supported, the tools should be modified to:

1. The tpm2_createpolicy tool not print the session handle but instead do a TPM2_ContextSave().
2. The tools get a session context instead of a handle and do a TPM2_ContextLoad()
3. The tools set the session continueSession attribute to SET and do a TPM2_ContextLoad(), since sessions can only be loaded once so the old one created by tpm2_createpolicy will already be invalid.
4. Have a tpm2_session_flush tool or something that flushes the session when is not needed anymore or the tools have an option to set continueSession attribute to CLEAR.

Thoughts? I don't know if @idesai is following this discussion but it would be very good to have his input since he did most of the session changes in the tpm2-tools.

**Comment by webmeister** [comment]
>  I'd much rather a connection need to be in possession of the context blob in order to continue a session. This requires that the context blob be passed to the holder of this new connection explicitly. This will allow any number of access control things be used to constrain the mechanism used to pass the blob.

This sounds like the correct approach to me. It may be a little easier to pass around handles instead of blobs, but there is no strong reason not to use blobs. Users are already used to that anyway for object blobs, so doing the same for sessions should not be a problem.

> I didn't find in any part of the specification an explicit relation between the connections and the sessions.

There was this quote from the specification "Session contexts MUST be loadable by the same connection that saved them". Allowing also other connections to load those contexts does not seem to contradict the statement.

> But to prevent those spammy users, maybe the LRU algorithm could have some heuristics and for example penalize sessions that were created in the same connection but never used or something along those lines?

Whatever algorithm you come up with, there will be someone who intentionally or unintentionally works around it. If you want to prevent DoS attacks, having hard limits/guaranteed resources as suggested by @flihp is the only way.

> If there's a fixed number of sessions that the TPM can have saved at a time (~64?) then we can make sure we're under this limit through a combination of connection limits and limits on sessions per connection.

How exactly would this work if you allow session contexts to be loaded by different connections? Then even if you set a limit of one saved session per connection, I could just create 64 connections (not at the same time, but one after the other) and save a session with each connection to exhaust the limit.

**Comment by martinezjavier** [comment]
> This sounds like the correct approach to me. It may be a little easier to pass around handles instead of blobs, but there is no strong reason not to use blobs. Users are already used to that anyway for object blobs, so doing the same for sessions should not be a problem.

@webmeister Yes, I do agree with @flihp and you.

My point was that this isn't what I understood in https://github.com/01org/tpm2-tools/issues/510 from @williamcroberts and @idesai explanations. IIUC they mentioned that the tpm2-abrmd should be modified to keep the sessions alive between connections, even if their contexts have not been saved.

And that's exactly what the tpm2-tools expect, since tpm2_createpolicy prints the session handle and the assumption is that this handle should be passed to the tools. The tools neither have an option to load a saved session context nor save a session context after a command that uses sessions.

So I just asked if restricting to sessions whose context have been saved was a deliberate design decision and if that's the case, to document this and modify the tools accordingly.

> There was this quote from the specification "Session contexts MUST be loadable by the same connection that saved them". Allowing also other connections to load those contexts does not seem to contradict the statement.

Right, I read that before but that's for sessions whose contexts have been saved. What I tried to say is that I didn't find a place where says that not saved sessions can't be used by other connections or that not saved sessions should be flushed after a connection closes.

In fact the whole concept of connection isn't properly defined in the specification AFAICT.

**Comment by flihp** [comment]
> How exactly would this work if you allow session contexts to be loaded by different connections? Then even if you set a limit of one saved session per connection, I could just create 64 connections (not at the same time, but one after the other) and save a session with each connection to exhaust the limit.

@webmeister: I'm not entirely sure how this will work. I can't see any real reason to allow a connection to continue more than a single session but as you point out, this just shifts the problem. In any case I think we'll need an administrative interface to flush sessions that have been continued but not claimed by another connection.

In any case it's probably a good idea to document this on the wiki.

**Comment by webmeister** [comment]
> What I tried to say is that I didn't find a place where says that not saved sessions can't be used by other connections or that not saved sessions should be flushed after a connection closes.

Found it: "The TAB MUST prevent connections from accessing transient handles or session handles that belong to other connections." ([Chapter 3.7 Isolation](https://trustedcomputinggroup.org/wp-content/uploads/TSS-TAB-and-Resource-Manager-ver1.0-rev16_Public_Review.pdf))

And also: "When the TAB/RM discovers that a connection is shutdown [...]: The RM SHOULD flush any objects, sequences, or sessions owned by the connection" (Chapter 3.12 Connection Shutdown)

Together that makes it pretty clear that sessions should not be shared between multiple connections. If we do support it nonetheless (by passing the session context blobs around), this functionality should probably be off by default, so that a user needs to explicitly enable it (and is then aware of the consequences, e.g. manual recovery, see below).

> In any case I think we'll need an administrative interface to flush sessions that have been continued but not claimed by another connection.

Administrative interface in the sense of a manual way for the admin to recover when things break? I cannot really see a way to automatically recover from such a situation without potentially breaking other scenarios.

**Comment by martinezjavier** [comment]
> Found it: "The TAB MUST prevent connections from accessing transient handles or session handles that belong to other connections." (Chapter 3.7 Isolation)
> 
> And also: "When the TAB/RM discovers that a connection is shutdown [...]: The RM SHOULD flush any objects, sequences, or sessions owned by the connection" (Chapter 3.12 Connection Shutdown)

@webmeister Thanks a lot for the pointer. This is a document that I still didn't find time to read in detail.

> Together that makes it pretty clear that sessions should not be shared between multiple connections. If we do support it nonetheless (by passing the session context blobs around), this functionality should probably be off by default, so that a user needs to explicitly enable it (and is then aware of the consequences, e.g. manual recovery, see below).

Agreed after reading what you shared. And IMHO the tools should be modified to not expect a session handle as I mentioned before.

BTW: I'm on paternity leave for some weeks, so I may not be able to follow discussions during that time.

**Comment by flihp** [comment]
> Together that makes it pretty clear that sessions should not be shared between multiple connections. If we do support it nonetheless (by passing the session context blobs around), this functionality should probably be off by default, so that a user needs to explicitly enable it (and is then aware of the consequences, e.g. manual recovery, see below).

From what I've been able to find out, this feature didn't make it into the spec for this very reason. Being able to pass a session from one connection to the next is extremely useful but LRU algorithms for eviction make for bugs with weird timing behaviors (aka "heisenbugs"). The language from the spec:

> When the TAB/RM discovers that a connection is shutdown [...]: The RM SHOULD flush any objects, sequences, or sessions owned by the connection" (Chapter 3.12 Connection Shutdown)

doesn't prohibit this behavior (SHOULD, not MUST) but it seems to strongly discourage it. I'm definitely open to alternatives and it may be that allowing a session to be passed from one process to another ends up being a better approach. My goal is to prototype both so that we can weigh pros / cons side by side.

Thanks again for helping collect the data in this thread. Very helpful.

**Comment by flihp** [comment]
the LRU implementation went in a while back: 209fc962fc8eea56119a789498c949e1e5aaa963
